# Generated by Django 2.0.7 on 2019-12-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191203_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default='this is cool', null=True),
        ),
    ]
