# Generated by Django 2.0.7 on 2019-12-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='presente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='in_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='out_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='placa',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
