# Generated by Django 2.0.7 on 2019-12-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0002_auto_20191224_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='in_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
